spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    active: local

---
# 로컬
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test; #메모리
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 9090

file:
  upload-dir: D:\attach\SIDE\QR